name: 🐛 Bug
description: Bir hata bildirin
title: "[BUG] "
labels: ["bug"]
assignees: []

body:
  - type: textarea
    id: description
    attributes:
      label: Ne oluyor?
      placeholder: "SOS butonu tıklayınca uygulama çöküyor"
    validations:
      required: true
  
  - type: textarea
    id: steps
    attributes:
      label: Nasıl tekrar edilir?
      placeholder: |
        1. Ana ekrana git
        2. SOS butonuna tıkla
        3. Çöküyor
    validations:
      required: true
  
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      options:
        - Android
        - iOS
        - Her ikisi
    validations:
      required: true
