name: ✨ Yeni Özellik
description: Özellik önerisi
title: "[FEATURE] "
labels: ["enhancement"]
assignees: []

body:
  - type: textarea
    id: description
    attributes:
      label: Ne istersin?
      placeholder: "Dark mode olsun, gece kullanırken göz yoruyor"
    validations:
      required: true
  
  - type: textarea
    id: why
    attributes:
      label: Neden gerekli?
      placeholder: "Battery de tasarruf eder, afet anında pil önemli"
    validations:
      required: true
